/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Panels;

import Controller.ServicoFilme;
import Controller.ServicoReserva;
import Model.Filme;
import Model.Reserva;
import Util.NotificacaoPopup;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kashiki
 */
public class ReservaPanel extends javax.swing.JPanel implements PropertyChangeListener {

    private final NotificacaoPopup popup;
    private final ServicoFilme servicoFilme;
    private final ServicoReserva servicoReserva;
    private final DefaultTableModel tableModel;

    /**
     * Creates new form Filme
     *
     * @param servicoFilme
     */
    public ReservaPanel(ServicoFilme servicoFilme) {
        initComponents();

        tableModel = (DefaultTableModel) this.tableReservas.getModel();

        this.servicoReserva = new ServicoReserva(servicoFilme);

        this.servicoFilme = servicoFilme;
        this.popup = new NotificacaoPopup();

        this.onLoadFilmes();

        this.servicoFilme.addPropertyChangeListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReservas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearchBoxClientName = new javax.swing.JTextField();
        btnSearchReserva = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbFilmes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtQtdBilhetes = new javax.swing.JSpinner();
        btnCriarReserva = new javax.swing.JButton();

        setBackground(new java.awt.Color(45, 45, 45));
        setPreferredSize(new java.awt.Dimension(745, 468));

        jTabbedPane1.setBackground(new java.awt.Color(45, 45, 45));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(45, 45, 45));

        tableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Filme", "Bilhetes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableReservas);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome do cliente:");

        txtSearchBoxClientName.setBackground(new java.awt.Color(60, 60, 60));
        txtSearchBoxClientName.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        txtSearchBoxClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchReservaActionPerformed(evt);
            }
        });

        btnSearchReserva.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnSearchReserva.setText("Pesquisar");
        btnSearchReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchReservaActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jButton4.setText("Remover");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchBoxClientName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSearchBoxClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de reservas", jPanel2);

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do cliente:");

        txtNomeCliente.setBackground(new java.awt.Color(60, 60, 60));
        txtNomeCliente.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        txtNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selecionar filme:");

        cmbFilmes.setBackground(new java.awt.Color(60, 60, 60));
        cmbFilmes.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantidade de bilhetes");

        txtQtdBilhetes.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtQtdBilhetes.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnCriarReserva.setText("Criar reserva");
        btnCriarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCriarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(cmbFilmes, 0, 704, Short.MAX_VALUE)
                            .addComponent(txtQtdBilhetes))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQtdBilhetes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCriarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Criar reserva", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarReservaActionPerformed
        String nomeCliente = this.txtNomeCliente.getText().trim();
        Filme filme = (Filme) this.cmbFilmes.getSelectedItem();

        if (filme == null) {
            popup.showMessage("Erro", "Filme inválido!", JOptionPane.ERROR_MESSAGE);
        }

        int filmeId = filme.getId();
        int qtdBilhetes = (int) this.txtQtdBilhetes.getValue();

        Boolean isSuccess = this.servicoReserva.Cadastrar(nomeCliente, filmeId, qtdBilhetes);

        if (isSuccess) {
            popup.showMessage("Sucesso", "Reserva criada com sucesso!", JOptionPane.INFORMATION_MESSAGE);

            this.txtNomeCliente.setText("");
            this.cmbFilmes.setSelectedIndex(0);
            this.txtQtdBilhetes.setValue(0);

            this.onLoadTable();
        } else {
            popup.showMessage("Erro", "Reserva não criada!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCriarReservaActionPerformed

    private void btnSearchReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchReservaActionPerformed
        String clientName = txtSearchBoxClientName.getText().trim();

        if (clientName.isEmpty()) {
            this.onLoadTable();
            return;
        }

        List<Reserva> reservas = this.servicoReserva.Consultar(clientName);

        if (reservas.isEmpty()) {
            popup.showMessage("Erro", "Reserva não encontrada!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        tableModel.setRowCount(0);

        reservas.forEach(reserva -> tableModel.addRow(reserva.toObject()));
    }//GEN-LAST:event_btnSearchReservaActionPerformed

    private void onLoadFilmes() {
        this.cmbFilmes.removeAllItems();
        this.servicoFilme.Listar().forEach(f -> this.cmbFilmes.addItem(f));
    }

    private void onLoadTable() {
        tableModel.setRowCount(0);

        this.servicoReserva.Listar().forEach(r -> tableModel.addRow(r.toObject()));
    }

    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        if ("filmes".equals(pce.getPropertyName())) {
            SwingUtilities.invokeLater(this::onLoadFilmes);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarReserva;
    private javax.swing.JButton btnSearchReserva;
    private javax.swing.JComboBox<Filme> cmbFilmes;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableReservas;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JSpinner txtQtdBilhetes;
    private javax.swing.JTextField txtSearchBoxClientName;
    // End of variables declaration//GEN-END:variables
}
